server:
  port: 9090
  servlet:
    context-path: /api/miaomiaole


spring:
  datasource:
    url: jdbc:mysql://122.51.103.202/springboot/useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 10086
    driver-class-name: com.mysql.jdbc.Driver
  profiles:
    active: dev
  kafka:
    bootstrap-servers:
      - 127.0.0.1:9092
    template:
      default-topic: miaomiaole
    consumer:
        group-id: kafka2
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.apache.kafka.common.serialization.StringSerializer
logging:
  level:
    root: info





