server:
  port: 9090
  servlet:
    context-path: /api/miaomiaole


spring:
  datasource:
    url: jdbc:mysql://122.51.103.202/springboot/useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 10086
    driver-class-name: com.mysql.jdbc.Driver
  profiles:
    active: dev
  kafka:
    bootstrap-servers:
      - 122.51.103.202:9092
    template:
      default-topic: miaomiaole
    consumer:
        group-id: kafka2
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.apache.kafka.common.serialization.StringSerializer
          retries: 2 #失败后重复发送的次数
          compression-type: gzip  #压缩格式
          batch-size: 1024 #批量发送消息的数量
  mail:
    host: smtp.163.com
    port: 25
    username: tom12510@163.com
    password: borndifferent.1
    default-encoding: utf-8

logging:
  level:
    root: info





