server:
  port: 9090
  servlet:
    context-path: /api/miaomiaole


spring:
  datasource:
    url: jdbc:mysql://122.51.103.202/springboot/useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 10086
    driver-class-name: com.mysql.jdbc.Driver
  profiles:
    active: dev


logging:
  level:
    root: info





